### ISSUE TITLE
Setting for Sublime Merge path

### ISSUE THREAD

**Issue by Zwyx** [adhamu/history-in-sublime-merge#15]
Hi and thank you for making this extension!

I would like to add the possibility of changing the Sublime Merge's path. I'm keen to create the PR for it if you're ok with it?

The reason is that [Sublime Merge loses all you open tabs if you open it with parameters](https://github.com/sublimehq/sublime_merge/issues/309). It's a pain and it makes me waste time reopening my 15 tabs.

So the possibility of changing the path in the extension will allow me to direct the command to this file, which I use when starting Sublime Merge through the command line; it checks that Sublime Merge is running before running its command:

```bash
#!/bin/bash

set -e

if pgrep sublime_merge; then
	if [[ -d $1 ]]; then
		/opt/sublime_merge/sublime_merge "$1"
	else
		/opt/sublime_merge/sublime_merge "$(dirname "$1")"
	fi
else
	xmessage "Start Sublime Merge before to prevent losing all open tabs."
fi
```

Are you ok with that? If yes, I'll prepare the PR adding this setting to the extension.

**Comment by adhamu** [comment]
Hey sure, happy to have a look at a PR

**Comment by Zwyx** [comment]
Thanks! PR opened here: https://github.com/adhamu/history-in-sublime-merge/pull/16
