### ISSUE TITLE
Feature request: jump to line upon blaming

### ISSUE THREAD

**Issue by ajitid** [adhamu/history-in-sublime-merge#17]
Sublime merge does provides a way to jump a specific line number as well: https://forum.sublimetext.com/t/goto-line-number/59567/3

Could we also send line no. to smerge as well?

**Comment by adhamu** [comment]
@ajitid I think that was the intention of the "View Line History in Sublime Merge" command

<img width="313" alt="Screenshot 2024-01-30 at 12 21 10" src="https://github.com/adhamu/history-in-sublime-merge/assets/4592613/ab8a62fa-4805-4179-bd47-0afb8bcb60d4">

**Comment by ajitid** [comment]
Looks like the output of `git log -L<start line>,<end line>:<filename>` is slightly different to "View Line History in Sublime Merge", but yeah that's probably what I was looking for instead of line blame.

Curious, given that Line History command exists, when do you find the use of Blame File command?

**Comment by adhamu** [comment]
Tbh, the main command I use is View File History
